name: nobryo_final
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Banco de Dados Local
  sqflite: ^2.3.3+1 

  # Firebase
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.7

  # Checagem de Conectividade
  connectivity_plus: ^6.0.3

  # Utilitários
  intl: ^0.19.0 # Para formatação de datas
  uuid: ^4.4.0 # Para gerar IDs únicos offline
  excel: ^2.1.0 # Para criar e manipular arquivos .xlsx
  path_provider: ^2.1.3 # Para encontrar os caminhos de diretório do dispositivo
  open_file: ^3.3.2 # Para abrir o arquivo gerado
  permission_handler: ^11.3.1 # Para solicitar permissões de armazenamento
  pdf: ^3.11.0
  image_picker: ^1.1.2
  collection: ^1.18.0
  shared_preferences: ^2.2.3
  provider: ^6.1.5
  flutter_time_picker_spinner: ^2.0.0

  # .env
  flutter_dotenv: ^5.1.0

  # Notificações
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - .env
    - assets/fonts/

  fonts:
      - family: Roboto
        fonts:
          - asset: assets/fonts/Roboto-Regular.ttf
          - asset: assets/fonts/Roboto-Bold.ttf
            weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.jpg"
